name: Validate Python

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v3

      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: ${{ matrix.python-version }}
          cache: true

      - name: Install dependencies
        run: pdm install

      - name: Test with pytest
        run: pdm run pytest

      - name: Lint with mypy
        run: pdm run mypy .

      - name: Lint with black
        run: pdm run black --check .

      - name: Lint with isort
        run: pdm run isort --check-only --profile black .

      - name: Lint with flake8
        run: pdm run flake8 . --count --show-source --statistics
